### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by minjurul** [eschultze/URLextractor#3]
./extractor.sh: 13: ./extractor.sh: source: not found
-e \e[1;32m##################################################
-e #                  URLextractor                  #
-e # Information Gathering & Website Reconnaissance #
-e #              coded by eschultze                #
-e #                version - 0.1.9                 #
-e ##################################################\e[m
[INFO] Date: 28/08/17 | Time: 01:52:10
./extractor.sh: 27: ./extractor.sh: [[: not found
./extractor.sh: 156: ./extractor.sh: Syntax error: Bad for loop variable

**Comment by eschultze** [comment]
Hi, it looks like you are trying to run the code and the file config.sh is not in the same folder.
